export const IDENTIFICATION_PROGRESS = "IDENTIFICATION_PROGRESS";
export const IDENTIFICATION_SELECT = "IDENTIFICATION_SELECT";
export const IDENTIFICATION_NEXT_STEP = "IDENTIFICATION_NEXT_STEP";
export const IDENTIFICATION_RESET = "IDENTIFICATION_RESET";
export const IDENTIFICATION_TYPES = ["aedes", "culex", "anopheles"]
